source 'https://github.com/rarnu/RarnuSpecs.git'

platform :ios, '10.0'
inhibit_all_warnings!

project 'YuGiOhCard.xcodeproj'

target 'YuGiOhCard' do
    use_frameworks!
    pod 'sfunctional'
    pod 'TangramKit'
end
