source 'https://github.com/codemonarch/MonarchSpec.git'

platform :ios, '10.0'
inhibit_all_warnings!

project 'YuGiOhCard.xcodeproj'

target 'YuGiOhCard' do
    use_frameworks!
    pod 'commonios'
    pod 'TangramKit'
end
