import UIKit

let ARR1 = "↙"
let ARR2 = "↓"
let ARR3 = "↘"
let ARR4 = "←"
let ARR6 = "→"
let ARR7 = "↖"
let ARR8 = "↑"
let ARR9 = "↗"

let _campDefault = "OCG、TCG"
let _commonDefault = "不限"
let _monster = "怪兽"
let _magic = "魔法"
let _trap = "陷阱"

let CAMP_OCG = "OCG"
let CAMP_TCG = "TCG"

let CT_MONSTER_NORMAL = "通常怪兽"
let CT_MONSTER_EFFECT = "效果怪兽"
let CT_MONSTER_SYNCHRO = "同调怪兽"
let CT_MONSTER_FUSION = "融合怪兽"
let CT_MONSTER_RITUAL = "仪式怪兽"
let CT_MONSTER_XYZ = "XYZ怪兽"
let CT_MONSTER_LINK = "连接怪兽"

let CT_MAGIC_NORMAL = "通常魔法"
let CT_MAGIC_FIELD = "场地魔法"
let CT_MAGIC_SPEED = "速攻魔法"
let CT_MAGIC_EQUIP = "装备魔法"
let CT_MAGIC_RITUAL = "仪式魔法"
let CT_MAGIC_CONTINIOUS = "永续魔法"

let CT_TRAP_NORMAL = "通常陷阱"
let CT_TRAP_COUNTER = "反击陷阱"
let CT_TRAP_CONTINIOUS = "永续陷阱"

let LINE = "--------------------------------------------------\n"
let CARD_BASE_INFO = "卡片名称: %@\n日文名称: %@\n英文名称: %@\n卡片种类: %@\n"
let CARD_XYZ = "XYZ"
let CARD_RANK = " 阶"
let CARD_MONSTER_INFO = "卡片属性: %@\n星数阶级: %@\n卡片种族: %@\n攻击力: %@\n守备力: %@\n"
let CARD_EXTRA_INFO = "卡片限制: %@\n所在卡包: %@\n卡片归属: %@\n卡片密码: %@\n罕贵程度: %@\n"
let CARD_EFFECT_INFO = "卡片效果: \n%@\n"

let MONSTER_TOON = "卡通"
let MONSTER_SPIRIT = "灵魂"
let MONSTER_UNION = "同盟"
let MONSTER_TUNNER = "调整"
let MONSTER_DOUBLE = "二重"
let MONSTER_REVERSE = "反转"
let MONSTER_PENDULUM = "灵摆"
let MONSTER_LINK = "连接"

let MONSTER_PENDULUM_SCALE = "灵摆刻度: 左(%ld)右(%ld)\n"
let MONSTER_LINK_COUNT = "连接数: %d\n"
let MONSTER_LINK_ARROW = "连接箭头: %@\n"

let LEFT_MENU_SEARCH = "卡片搜索"
let LEFT_MENU_LIMIT = "禁限卡表"
let LEFT_MENU_LATEST = "最新卡片"
let LEFT_MENU_PACKAGE = "卡包"
let LEFT_MENU_FAV = "我的最爱"
let LEFT_MENU_TOOL = "决斗工具"

let RIGHT_MENU_SETTING = "系统设置"
let RIGHT_MENU_UPDATE = "检查新版本"
let RIGHT_MENU_FEEDBACK = "信息反馈"
let RIGHT_MENU_ABOUT = "关于本软件"

let TOOL_DICE = "骰子"
let TOOL_COIN = "硬币"

let COMMON_DONE = "完成"
let COMMON_CLOSE = "关闭"
let COMMON_REFRESH = "刷新"
let COMMON_CANCEL = "取消"
let COMMON_OK = "确定"

let STR_NO_CARD_COLLECTED = "还没有收藏的卡片"
let STR_RESULT = "卡片列表"
let STR_NO_CARD_FOUND = "没有找到任何卡片"
let STR_CONFIRM = "确认?"
let STR_CONFIRM_CLEAR_DOCUMENT = "确定要清空全部卡图吗，清空卡图后您将需要重新下载卡图。"
let STR_CARD_COUNT = "%d 张"
let STR_DOWNLOAD_UPDATE = "下载更新"
let STR_DOWNLOAD_NA = "无需更新"
let STR_PUBLIC_DATE = "发布日期：%@"

let RACE_WARRIOR = "战士"
let RACE_UNDEAD = "不死"
let RACE_DEMON = "恶魔"
let RACE_BEAST = "兽"
let RACE_BEAST_WARRIOR = "兽战士"
let RACE_DINOSAUR = "恐龙"
let RACE_FISH = "鱼"
let RACE_MACHINE = "机械"
let RACE_WATER = "水"
let RACE_ANGEL = "天使"
let RACE_MAGICIAN = "魔法师"
let RACE_FIRE = "炎"
let RACE_THUNDER = "雷"
let RACE_LIZARD = "爬虫类"
let RACE_PLANT = "植物"
let RACE_INSECT = "昆虫"
let RACE_STONE = "岩石"
let RACE_SEA_DRAGON = "海龙"
let RACE_BIRD = "鸟兽"
let RACE_DRAGON = "龙"
let RACE_MENTAL = "念动力"
let RACE_DREAM_DRAGON = "幻龙"
let RACE_CYBERSE = "电子界"
let RACE_GOD = "幻神兽"
let RACE_CREATION = "创造神"

let ATTR_EARTH = "地"
let ATTR_WATER = "水"
let ATTR_FIRE = "炎"
let ATTR_WIND = "风"
let ATTR_LIGHT = "光"
let ATTR_DARK = "暗"
let ATTR_GOD = "神"

let RARE_N = "平卡N"
let RARE_R = "银字R"
let RARE_GR = "黄金GR"
let RARE_NR = "平罕NR"
let RARE_SR = "面闪SR"
let RARE_UR = "金字UR"
let RARE_PR = "爆闪PR"
let RARE_HR = "全息HR"
let RARE_GHR = "鬼闪GHR"
let RARE_NPR = "平爆NPR"
let RARE_RUR = "红字RUR"
let RARE_SCR = "斜碎SCR"
let RARE_SER = "银碎SER"
let RARE_USR = "金碎USR"
let RARE_UTR = "立体UTR"

let LIMIT_NONE = "无限制"
let LIMIT_BAN = "禁止卡"
let LIMIT_LIMIT = "限制卡"
let LIMIT_LIMIT_2 = "准限制卡"
let LIMIT_SHOWN = "观赏卡"
