#import <Foundation/Foundation.h>

#define _campDefault @"OCG、TCG"
#define _commonDefault @"不限"
#define _monster @"怪兽"
#define _magic @"魔法"
#define _trap @"陷阱"

#define CAMP_OCG @"OCG"
#define CAMP_TCG @"TCG"

#define CT_MONSTER_NORMAL @"通常怪兽"
#define CT_MONSTER_EFFECT @"效果怪兽"
#define CT_MONSTER_SYNCHRO @"同调怪兽"
#define CT_MONSTER_FUSION @"融合怪兽"
#define CT_MONSTER_RITUAL @"仪式怪兽"
#define CT_MONSTER_XYZ @"XYZ怪兽"

#define CT_MAGIC_NORMAL @"通常魔法"
#define CT_MAGIC_FIELD @"场地魔法"
#define CT_MAGIC_SPEED @"速攻魔法"
#define CT_MAGIC_EQUIP @"装备魔法"
#define CT_MAGIC_RITUAL @"仪式魔法"
#define CT_MAGIC_CONTINIOUS @"永续魔法"

#define CT_TRAP_NORMAL @"通常陷阱"
#define CT_TRAP_COUNTER @"反击陷阱"
#define CT_TRAP_CONTINIOUS @"永续陷阱"

#define LINE @"--------------------------------------------------\n"
#define CARD_BASE_INFO @"卡片名称: %@\n日文名称: %@\n英文名称: %@\n卡片种类: %@\n"
#define CARD_XYZ @"XYZ"
#define CARD_RANK @" 阶"
#define CARD_MONSTER_INFO @"卡片属性: %@\n星数阶级: %@\n卡片种族: %@\n攻击力: %@\n守备力: %@\n"
#define CARD_EXTRA_INFO @"卡片限制: %@\n所在卡包: %@\n卡片归属: %@\n卡片密码: %@\n罕贵程度: %@\n"
#define CARD_EFFECT_INFO @"卡片效果: \n%@\n"

#define MONSTER_TOON @"卡通"
#define MONSTER_SPIRIT @"灵魂"
#define MONSTER_UNION @"同盟"
#define MONSTER_TUNNER @"调整"
#define MONSTER_DOUBLE @"二重"
#define MONSTER_REVERSE @"反转"
#define MONSTER_PENDULUM @"灵摆"

#define MONSTER_PENDULUM_SCALE @"灵摆刻度: 左(%ld)右(%ld)\n"

#define LEFT_MENU_SEARCH @"卡片搜索"
#define LEFT_MENU_LIMIT @"禁限卡表"
#define LEFT_MENU_LATEST @"最新卡片"
#define LEFT_MENU_PACKAGE @"卡包"
#define LEFT_MENU_FAV @"我的最爱"
#define LEFT_MENU_TOOL @"决斗工具"

#define RIGHT_MENU_SETTING @"系统设置"
#define RIGHT_MENU_UPDATE @"检查新版本"
#define RIGHT_MENU_FEEDBACK @"信息反馈"
#define RIGHT_MENU_ABOUT @"关于本软件"

#define TOOL_DICE @"骰子"
#define TOOL_COIN @"硬币"

#define COMMON_DONE @"完成"
#define COMMON_CLOSE @"关闭"
#define COMMON_REFRESH @"刷新"
#define COMMON_CANCEL @"取消"
#define COMMON_OK @"确定"

#define STR_NO_CARD_COLLECTED @"还没有收藏的卡片"
#define STR_RESULT @"卡片列表"
#define STR_NO_CARD_FOUND @"没有找到任何卡片"
#define STR_CONFIRM @"确认?"
#define STR_CONFIRM_CLEAR_DOCUMENT @"确定要清空全部卡图吗，清空卡图后您将需要重新下载卡图。"
#define STR_CARD_COUNT @"%d 张"
#define STR_DOWNLOAD_UPDATE @"下载更新"
#define STR_DOWNLOAD_NA @"无需更新"

#define RACE_WARRIOR @"战士"
#define RACE_UNDEAD @"不死"
#define RACE_DEMON @"恶魔"
#define RACE_BEAST @"兽"
#define RACE_BEAST_WARRIOR @"兽战士"
#define RACE_DINOSAUR @"恐龙"
#define RACE_FISH @"鱼"
#define RACE_MACHINE @"机械"
#define RACE_WATER @"水"
#define RACE_ANGEL @"天使"
#define RACE_MAGICIAN @"魔法师"
#define RACE_FIRE @"炎"
#define RACE_THUNDER @"雷"
#define RACE_LIZARD @"爬虫类"
#define RACE_PLANT @"植物"
#define RACE_INSECT @"昆虫"
#define RACE_STONE @"岩石"
#define RACE_SEA_DRAGON @"海龙"
#define RACE_BIRD @"鸟兽"
#define RACE_DRAGON @"龙"
#define RACE_MENTAL @"念动力"
#define RACE_DREAM_DRAGON @"幻龙"
#define RACE_GOD @"幻神兽"

#define ATTR_EARTH @"地"
#define ATTR_WATER @"水"
#define ATTR_FIRE @"炎"
#define ATTR_WIND @"风"
#define ATTR_LIGHT @"光"
#define ATTR_DARK @"暗"
#define ATTR_GOD @"神"

#define RARE_N @"平卡N"
#define RARE_R @"银字R"
#define RARE_GR @"黄金GR"
#define RARE_NR @"平罕NR"
#define RARE_SR @"面闪SR"
#define RARE_UR @"金字UR"
#define RARE_PR @"爆闪PR"
#define RARE_HR @"全息HR"
#define RARE_GHR @"鬼闪GHR"
#define RARE_NPR @"平爆NPR"
#define RARE_RUR @"红字RUR"
#define RARE_SCR @"斜碎SCR"
#define RARE_SER @"银碎SER"
#define RARE_USR @"金碎USR"
#define RARE_UTR @"立体UTR"

#define LIMIT_NONE @"无限制"
#define LIMIT_BAN @"禁止卡"
#define LIMIT_LIMIT @"限制卡"
#define LIMIT_LIMIT_2 @"准限制卡"
#define LIMIT_SHOWN @"观赏卡"
